@extends('layouts.admi')

    @section('title') 
        @parent
    @stop
    @section('header')
	   @parent
    @stop
    @section('menusup')
        @parent   
    @stop
    @section('menuizq')
        @parent   
    @stop
    @section('content')
        @parent
    @stop 
    @section('menuder')
        @parent
    @stop
    @section('footer')
	   @parent
    @stop